name: humanid_flutter_sdk
description: Human ID Flutter SDK
version: 0.0.5
homepage: https://human-id.org
documentation: https://github.com/bluenumberfoundation/humanid-fluttersdk

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #network
  dio: ^4.0.6
  retrofit: ^3.0.1+1

  #model
  equatable: ^2.0.5
  json_serializable: ^6.4.0
  json_annotation : ^4.7.0

  #injection
  get_it: ^7.2.0

  #bloc
  flutter_bloc: ^8.1.1

  #utils
  logger: ^1.1.0

  #UI
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.5
  hexcolor: ^2.0.7
  intl: ^0.17.0

  #WebView
  flutter_inappwebview: ^5.4.3+7

  #freezed
  freezed_annotation: ^2.0.4

  #downloader
  flutter_downloader: ^1.8.4

  #path
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  retrofit_generator: ^4.0.3+2
  alice: ^0.2.5
  freezed: ^2.0.4

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.humanid.humanid_flutter_sdk
        pluginClass: HumanidFlutterSdkPlugin
      ios:
        pluginClass: HumanidFlutterSdkPlugin

  assets:
    - assets/images/
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
